config/routes.rb
Rails.application.routes.draw do

  resources :messages
  root 'site#index'

  get "/index" => 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'messages#new'

  post '/contact' => 'inquiries#create'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Thanks for contacting me. I'll get back to you soon." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
 

  # DELETE /messages/1
  # DELETE /messages/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :company, :phone, :email, :subject, :body)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	
	def index
	end

	def about
	end

	def contact
	end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/inquiries/new.html.erb
    <div id="wrapper" style="text-align: center">
      <div class="left">
        <p id="brief">Email contact is preferred, though urgent matters are best discussed by phone. Please only contact me via facebook if I actually know you; this is available merely as reference.</p>      
      </div>
      <div class="right">  <ul class="contact-info">
          <li class="phone"><a href="tel:(+64)278418623"> 0278418623 </a><li>
          <li class="facebook"><a href="https://www.facebook.com/messages/campbell.hawkes">Message Me on Facebook</a></li>
          <li class="mail"><a href="mailto:mr.campbell.hawkes@gmail.com">mr.campbell.hawkes@gmail.com</a></li>
        <form method="post" action="/contact">
          <fieldset class="form">
            <legend>Send us a message</legend>
            <div class="form-group">
              <label for="message">Message</label> <br>
              <textarea id="message" name="message" class="form-control"></textarea>
              <input type="submit" value="Send" class="button" id="submit">
            </div>
          </fieldset>

          <%= render 'form' %>
        </form>

      </div>
    
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="<u></u>tf-10">
    <title>Campbell Hawkes | Winter</title>
    <link href='http://fonts.googleapis.com/css?family=Arimo:400italic,400,700italic,700|Josefin+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'normalize', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
        <%= link_to_unless_current "Campbell Hawkes",
          root_path, id: "head-link" do |label|
            content_tag(:span, label, id: "head-link")
          end
        %>

         </h1>
          <h2>Athlete and Creator of Things</h2>
        </a>
    </header>
    <div id="navpanel">
      <nav>
        <ul>
        <li> 
          <p><%= link_to_unless_current "Previous_Work", root_path do 
            |label| content_tag(:span,label,class: "current")
            end %></p> 
        </li>
        <li> <p> <%= link_to_unless_current "Who_am_I?", about_path do 
          |label| content_tag(:span,label,class: "current")
          end %> </p>
        </li>
        <li> <p><%= link_to_unless_current "Contact_Me", contact_path do
        |label| content_tag(:span,label,class: "current")
        end %> </p></li>
        </ul>
      </nav>
    </div>
    
    <% if flash.alert %>
          <div class="messages">
            <div class="alert alert-danger" role="alert">
              <%= flash.alert %>
            </div>
          </div>
        <% end %>

      <% if flash.notice %>
        <div class="messages">
          <div class="alert alert-success" role="alert">
            <%= flash.notice %>
          </div>
        </div>
      <% end %>

    <%= yield %>
    
    <footer>
      <box id="linebreak">
      </box>
      <div class="footer-elements">
          <a alt="Link to Campbell's Facebook Profile" class="social_links" href="http://www.facebook.com/campbell.hawkes"><%= image_tag "facebook-small.png" %></a>
          <p> &copy; 2015 - Campbell Hawkes.</p>
      </div>
    </footer>
  </body>
</html>

app/views/messages/_contact.html.erb
 <ul class="contact-info">
 <li class="phone"><a href="tel:(+64)278418623"> 0278418623 </a><li>
          <li class="facebook"><a href="https://www.facebook.com/messages/campbell.hawkes">Message Me on Facebook</a></li>
          <li class="mail"><a href="mailto:mr.campbell.hawkes@gmail.com">mr.campbell.hawkes@gmail.com</a></li>

app/views/messages/_form.html.erb
<div class="form">
  <%= form_for(@message) do |f| %>
    <% if @message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
        <% @message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :company %><br>
      <%= f.text_field :company %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :subject %><br>
      <%= f.text_field :subject %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit "Send", :id => "submit" %>
    </div>
  <% end %>
</div>

app/views/messages/new.html.erb
    <div id="wrapper" style="text-align: center">
      <div class="left">
        <p id="brief">Email contact is preferred, though urgent matters are best discussed by phone. Please only contact me via facebook if I actually know you; this is available merely as reference.</p>      
      </div>
      <div class="right">  <ul class="contact-info">
         <%= render 'contact' %>
       <!--  <form method="post" action="/contact">
          <fieldset class="form">
            <legend>Send us a message</legend>
            <div class="form-group">
              <label for="message">Message</label> <br>
              <textarea id="message" name="message" class="form-control"></textarea>
              <input type="submit" value="Send" class="button" id="submit">
            </div>
          </fieldset>
        </form>
 -->
      </div>
          <%= render 'form' %>

    
    </div> 

app/views/messages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @message.name.split(" ").first %>
</p>

<p>
  <strong>Company:</strong>
  <%= @message.company %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @message.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @message.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/site/about.html.erb
      <div id="profile">
        <ul id="bio">
          <li><p class="bio">I'm Campbell; a New Zealand citizen with aspirations in web design. This is (evidently) a project site, within which I will be experimenting through the course of <a href="http://devacademy.co.nz/"> Enspiral Dev Academy's "Dev Bootcamp"</a> course and beyond. Watch this space!</p> </li>
          <li>  <%= image_tag "BnWsquare.jpg", class:"profile_pic" %>
          	<!-- <alt="Campbell's Profile Image" class="profile_pic"> -->
          </li>
      </div>

app/views/site/index.html.erb
    <div id="wrapper">
      <section>
        <p> A short collection of images </p>
        <ul id="gallery">
          <li><a href="img/Frontflip.jpg" alt="">
            <%= image_tag("Frontflip.jpg", alt: "Image: Campbell Hawkes, Mt Hutt, New Zealand") %>
            <!-- <img src="img/Frontflip.jpg" alt="Skier: Campbell Hawkes"> -->
            <p>Skier: Campbell Hawkes
            Image Credit: Angus Ward
            Location: Mt Hutt, NZ</p></a>
          </li>
            <li><a href="img/Flatfive.jpg"><%= image_tag("Flatfive.jpg", alt: "Image: Campbell Hawkes, Mt Hutt, New Zealand") %><p>Skier: Campbell Hawkes 
            Image Credit: Chris McLean
            Location: Mt Hutt, NZ</p></a>
          </li>
          <li><a href="img/JNATScliff.jpg"><%= image_tag("JNATScliff.jpg", alt: "Image: Campbell Hawkes, Cardrona, New Zealand")  %><p>Skier: Campbell Hawkes 
          Credit: Chris Burrel-Smith
          Location: Cardrona, NZ</p></a></li>
        </ul>
      </section>
    </div>  